CREATE TABLE Sys_VisitorLog
(
	F_Id varchar(50) PRIMARY KEY not null,
	F_WebSiteId varchar(50),
	F_WebSiteName varchar(200),
	F_UrlAddress varchar(200),
	F_Point varchar(200),
	F_ModuleName nvarchar(50),
	F_SourceBrowser varchar(200) NULL,
	F_IP nvarchar(50),
	F_SourceType nvarchar(50),
	F_Area nvarchar(50),
	F_Address nvarchar(200), 
	F_Desc nvarchar(2000),
	F_EnabledMark bit NULL,
	F_DeleteMark bit NULL,
	F_MainMark bit NULL,
	F_CreatorUserId varchar(50) NULL,
	F_CreatorTime datetime NULL,
	F_DeleteUserId varchar(50) NULL,
	F_DeleteTime datetime NULL,
	F_LastModifyTime datetime NULL,
	F_LastModifyUserId varchar(50) NULL,
)