CREATE TABLE Sys_VisitorLogs
(
	Id varchar(50) PRIMARY KEY not null,
	WebSiteId varchar(50),
	WebSiteName varchar(200),
	UrlAddress varchar(200),
	Point varchar(200),
	ModuleName nvarchar(50),
	SourceBrowser varchar(200) NULL,
	IP nvarchar(50),
	SourceType nvarchar(50),
	Area nvarchar(50),
	Address nvarchar(200), 
	Description nvarchar(2000),
	EnabledMark bit NULL,
	DeleteMark bit NULL,
	MainMark bit NULL,
	CreatorUserId varchar(50) NULL,
	CreatorTime datetime NULL,
	DeleteUserId varchar(50) NULL,
	DeleteTime datetime NULL,
	LastModifyTime datetime NULL,
	LastModifyUserId varchar(50) NULL,
)