truncate table C_Columns
truncate table C_Contents
truncate table C_Templets
truncate table Sys_AccessLog
--truncate table Sys_Area
truncate table Sys_DbBackup
truncate table Sys_FilterIP
--truncate table Sys_Items
--truncate table Sys_ItemsDetail
truncate table Sys_Log
--truncate table Sys_Module
--truncate table Sys_ModuleButton
--truncate table Sys_ModuleForm
--truncate table Sys_ModuleFormInstance
--truncate table Sys_Organize
--truncate table Sys_Role
truncate table Sys_RoleAuthorize
truncate table Sys_UpFiles
--truncate table Sys_User
truncate table Sys_UserLogOn
truncate table Sys_UserWebSites
truncate table Sys_WebSiteForUrls
truncate table Sys_WebSites